const Villes = [
	"Les Avirons",
	"Bagatelle",
	"Basse-Terre",
	"Basse-Vallée",
	"Bellemène",
	"Belle-Pierre",
	"Bellevue",
	"Bérive",
	"Bernica",
	"Bois-Blanc",
	"Bois-Court",
	"Bois d'Olives",
	"Bois-de-Nèfles",
	"Bois-de-Nèfles",
	"Boucan Canot",
	"Bourg-Murat",
	"Bras des Chevrettes",
	"Bras-Panon",
	"La Bretagne",
	"Le Brulé",
	"La Cafrine",
	"Cambourg",
	"Cambuston",
	"Les Camélias",
	"La Chaloupe",
	"Le Chaudron",
	"Cilaos",
	"Les Colimaçons",
	"La Confiance",
	"La Créssonière",
	"La Découvèrte",
	"Domenjo",
	"Dos-d'Ane",
	"Entre-Deux",
	"L'Eperon",
	"Etang Saint-Leu",
	"Etang Saint-Paul",
	"Etang-Salé",
	"Fleurimont",
	"Gillot",
	"Gol-Les-Hauts",
	"Le Guillaume",
	"Grand-Fond",
	"Grand Ilet",
	"Grande-Chaloupe",
	"Grand-Bois",
	"Hell-Bourg",
	"Ermitage-Les-Bains",
	"Ermitage-Les-Hauts",
	"Langevin",
	"Les Lianes",
	"Mafate",
	"Manapany",
	"Les Makes",
	"La Mare",
	"Mare-a-Vielle-Place",
	"La Montagne",
	"Montgaillard",
	"Montvert",
	"Moufia",
	"Notre-Dame de la Paix",
	"Le Ouaki",
	"Palmiste-Rouge",
	"Le Pavillon",
	"Petit Serré",
	"Petite France",
	"Petie Ile",
	"Pierrefonds",
	"Piton Saint-Leu",
	"Piton Sainte-Rose",
	"Plaine Saint-Paul",
	"Plaine des Cafres",
	"Plaine des Palmistes",
	"Le Plate",
	"Plateau Caillou",
	"Pont d'Yves",
	"Le Port",
	"La Possession",
	"Quartier-Français",
	"Le 14ème",
	"Ravine A Malheur",
	"Ravine des Cabris",
	"La Rivière",
	"Rivière des Galets",
	"Rivière Du Mât",
	"Rivière Des Pluies",
	"Roche Plate",
	"Saint-André",
	"Saint-Benoît",
	"Saint-Bernard",
	"Saint-Denis",
	"Saint-François",
	"Saint-Gilles Les Bains",
	"Saint-Gilles les Hauts",
	"Saint-Joseph",
	"Saint-Leu",
	"Saint-Louis",
	"Saint-Paul",
	"Saint-Philippe",
	"Saint-Pierre",
	"Sainte-Anne",
	"Sainte-Clotilde",
	"Sainte-Marie",
	" Sainte-Rose",
	" Sainte-Suzanne",
	"Salazie",
	"La Saline",
	"Saline Les Bains",
	"Sans-Soucis",
	"Savannah",
	"Souris Chaude",
	"Le Tampon",
	"Tan-Rouge",
	"Terrain Elisa",
	"Terre Sainte",
	"Tévelave",
	"Le Tremblet",
	"Trois Mares",
	"Villèle",
	"Vincendo",
]
export default Villes;